spring.application.name=clinic-api

spring.datasource.url=jdbc:sqlite:clinic.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=jk.clinic_api.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=5050
openai.api.key=tu_api_key_aqui
app.testing=true